# Generated by Django 5.2.9 on 2026-01-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('input', 'Input Received'), ('maker', 'Maker Agent'), ('validation', 'Validation'), ('checker', 'Checker Agent'), ('complete', 'Pipeline Complete')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('prompt_sent', models.TextField(blank=True)),
                ('response_received', models.TextField(blank=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='accounting__session_28a19e_idx')],
            },
        ),
    ]
