# Generated by Django 5.2.4 on 2026-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_agentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('receipt_with_tds', 'Receipt with TDS'), ('salary', 'Salary'), ('expense', 'Expense'), ('drawings', 'Drawings'), ('capital', 'Capital')], max_length=20),
        ),
    ]
