# Generated by Django 5.2.4 on 2026-01-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_subtype',
            field=models.CharField(blank=True, help_text="Subtype for finer classification (e.g., 'sundry_debtors', 'security_deposit')", max_length=50),
        ),
    ]
