# Generated by Django 5.2.9 on 2026-01-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_migrate_shree_cement_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('receipt_with_tds', 'Receipt with TDS'), ('salary', 'Salary'), ('expense', 'Expense'), ('drawings', 'Drawings'), ('capital', 'Capital'), ('gst_payment', 'GST Payment')], max_length=20),
        ),
    ]
