# Generated by Django 5.2.4 on 2026-01-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journalentry_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='review_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Review checklist items completed'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='review_remarks',
            field=models.TextField(blank=True, help_text='Optional additional remarks from reviewer'),
        ),
    ]
