# Generated by Django 5.2.4 on 2026-01-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_journalentry_review_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='review_checklist',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='review_remarks',
        ),
    ]
