# Generated by Django 5.2.9 on 2026-01-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_journalentry_accounting__status_0a2ff9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('receipt_with_tds', 'Receipt with TDS'), ('salary', 'Salary'), ('salary_advance', 'Salary Advance'), ('salary_adjustment', 'Salary Adjustment'), ('expense', 'Expense'), ('drawings', 'Drawings'), ('capital', 'Capital'), ('gst_payment', 'GST Payment')], max_length=20),
        ),
    ]
